# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: double-entry-book-keeping
    tier: database
    environment: {{ .Values.environment }}
spec:
  # 레플리카 개수는 기본적으로 1이지만, 데이터베이스 pod이 오직 1개임을 보다 명시적으로 설정
  replicas: 1
  selector:
    matchLabels:
      app: double-entry-book-keeping
      tier: database
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: double-entry-book-keeping
        tier: database
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image }}
          imagePullPolicy: {{ .Values.database.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.database.port }}
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: db-secrets
              # 도커 시크릿과 일관되게 하기 위하여 /run/secrets로 시도했으나
              # 쿠버네티스에서 해당 디렉토리를 사용 중이라 대체 경로 설정
              mountPath: /etc/secrets
              readOnly: true
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.env.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.database.env.MYSQL_USER }}
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: {{ .Values.database.env.MYSQL_ROOT_PASSWORD_FILE }}
            - name: MYSQL_PASSWORD_FILE
              value: {{ .Values.database.env.MYSQL_PASSWORD_FILE }}
          livenessProbe:
            exec:
              command:
                - docker-healthcheck
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - docker-healthcheck
            failureThreshold: 6
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.database.resources.requests.cpu }}
              memory: {{ .Values.database.resources.requests.memory }}
            limits: 
              cpu: {{ .Values.database.resources.limits.cpu }}
              memory: {{ .Values.database.resources.limits.memory }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: double-entry-book-keeping-pvc
        - name: db-secrets
          secret:
            secretName: double-entry-book-keeping-database-secret
            defaultMode: 0400
