# prettier-ignore
apiVersion: v1
kind: Secret
metadata:
  name: double-entry-book-keeping-database-secret
  labels:
    app: double-entry-book-keeping
    tier: database
    environment: {{ .Values.environment }}
type: Opaque
stringData:
  # 추후 깃헙 시크릿으로 삽입하는 것으로 수정하고 여기서는 임시 값 작성
  # 도커 컴포즈의 시크릿 주입과 같은 형식 사용
  db_root_password: |
    {{ .Values.database.secret.db_root_password }}
  db_password: |
    {{ .Values.database.secret.db_password }}
