apiVersion: v1
kind: ConfigMap
metadata:
  name: double-entry-book-keeping-server-config
data:
  config.yaml: |
    environment: "development"
    jwt:
      expiresIn: "60s"
      cookie:
        maxAge: 60000
    client:
      host: "http://double-entry-book-keeping.com"
