apiVersion: v1
kind: Service
metadata:
  name: double-entry-book-keeping-server-service
  labels:
    app: double-entry-book-keeping
    tier: server
    environment: local
spec:
  ports:
    - port: 4000
      targetPort: 3000
  selector:
    app: double-entry-book-keeping
    tier: server
    environment: local
  type: LoadBalancer
