services:
  database: 
    build:
      context: ./database
    volumes:
      - double-entry-book-keeping-data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: "double-entry-book-keeping"
      MYSQL_USER: "user"
      MYSQL_ROOT_DATABASE_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    networks:
      - private
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src:/app/src:rw
      - ./server/prisma:/app/prisma:rw
      - ./server/package.json:/app/package.json:rw
      - ./server/package-lock.json:/app/package-lock.json:rw
    ports:
      - 4000:3000
    networks:
      - private
      - default
    secrets:
      - config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://server:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client/src:/app/src:rw
      - ./client/package.json:/app/package.json:rw
      - ./client/package-lock.json:/app/package-lock.json:rw
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://client:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    env_file:
      - ./env/development/.client.env


volumes:
  double-entry-book-keeping-data:

networks:
  private:

secrets:
  db_root_password:
    file: ./secret/development/db_root_password.txt
  db_password:
    file: ./secret/development/db_password.txt
  config.yaml:
    file: ./secret/development/config.yaml