services:
  database: 
    build:
      context: ./database
    volumes:
      - double-entry-book-keeping-data:/var/lib/mysql:rw
    env_file:
      - .database.env
    networks:
      - private
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src:/app/src:rw
      - ./server/prisma:/app/prisma:rw
      - ./server/package.json:/app/package.json:rw
      - ./server/package-lock.json:/app/package-lock.json:rw
    ports:
      - 4000:3000
    depends_on:
      - database
    networks:
      - private
      - default
    env_file:
      - ./server/.env
  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/app/src:rw
      - ./client/package.json:/app/package.json:rw
      - ./client/package-lock.json:/app/package-lock.json:rw
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - default

volumes:
  double-entry-book-keeping-data:

networks:
  private:
