services:
  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/app/src:rw
      - ./client/package.json:/app/package.json:rw
      - ./client/package-lock.json:/app/package-lock.json:rw
    ports:
      - 3000:3000
  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src:/app/src:rw
      - ./server/package.json:/app/package.json:rw
      - ./server/package-lock.json:/app/package-lock.json:rw
    ports:
      - 4000:3000