apiVersion: v1
kind: Service
metadata:
  name: double-entry-book-keeping-client-service
  labels:
    app: double-entry-book-keeping
    tier: client
    environment: local
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: double-entry-book-keeping
    tier: client
    environment: local
  type: ClusterIP
