apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: double-entry-book-keeping-pvc
  labels:
    app: double-entry-book-keeping
    tier: database
    environment: local
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: hostpath
  resources:
    requests:
      storage: 4Gi
