# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: double-entry-book-keeping
    tier: client
    environment: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: double-entry-book-keeping
      tier: client
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: double-entry-book-keeping
        tier: client
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: client
          image: {{ .Values.client.image }}
          imagePullPolicy: {{ .Values.client.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.client.targetPort }}
              name: client
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.client.targetPort }}
            failureThreshold: 4
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.targetPort }}
            periodSeconds: 30
          resources:
            requests:
              cpu: {{ .Values.client.resources.requests.cpu }}
              memory: {{ .Values.client.resources.requests.memory }}
            limits: 
              cpu: {{ .Values.client.resources.limits.cpu }}
              memory: {{ .Values.client.resources.limits.memory }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: double-entry-book-keeping-client-config
            defaultMode: 0400
