# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: double-entry-book-keeping
    tier: client
    environment: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: double-entry-book-keeping
      tier: client
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: double-entry-book-keeping
        tier: client
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: client
          image: {{ .Values.client.image }}
          imagePullPolicy: {{ .Values.client.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.client.targetPort }}
              name: client
          env:
            - name: REACT_APP_API_BASE_URL
              value: {{ .Values.client.env.REACT_APP_API_BASE_URL }}
            - name: SKIP_DEPENDENCY_CHECK
              value: {{ .Values.client.env.SKIP_DEPENDENCY_CHECK | quote }}
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.client.targetPort }}
            failureThreshold: 6
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.targetPort }}
            failureThreshold: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.client.targetPort }}
            failureThreshold: 1
            periodSeconds: 30
