# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: double-entry-book-keeping
    tier: server
    environment: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: double-entry-book-keeping
      tier: server
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: double-entry-book-keeping
        tier: server
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          imagePullPolicy: {{ .Values.server.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.server.targetPort }}
              name: server
          env:
            - name: NODE_ENV
              value: {{ .Values.environment | quote }}
          volumeMounts:
            - name: server-config
              mountPath: /etc/config
            - name: server-secret
              mountPath: /etc/secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.server.targetPort }}
            failureThreshold: 1
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.server.targetPort }}
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.server.targetPort }}
            failureThreshold: 6
            periodSeconds: 5
      volumes:
        - name: server-config
          configMap:
            name: double-entry-book-keeping-server-config
            defaultMode: 0400
        - name: server-secret
          secret:
            secretName: double-entry-book-keeping-server-secret
            defaultMode: 0400
