# prettier-ignore
apiVersion: v1
kind: Secret
metadata:
  name: double-entry-book-keeping-server-secret
  labels:
    app: double-entry-book-keeping
    environment: {{ .Values.environment }}
type: Opaque
stringData:
  secret.yaml: |
    database:
      url: {{ .Values.server.secret.database.url }}
    jwt:
      secret: {{ .Values.server.secret.jwt.secret }}
