# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: double-entry-book-keeping-server-service
  labels:
    app: double-entry-book-keeping
    tier: server
    environment: {{ .Values.environment }}
spec:
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.targetPort }}
  selector:
    app: double-entry-book-keeping
    tier: server
    environment: {{ .Values.environment }}
  type: ClusterIP
