# prettier-ignore
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: double-entry-book-keeping
    tier: grafana
    environment: {{ .Values.environment }}
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local:9090
        isDefault: true
        editable: true
