# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: double-entry-book-keeping
    tier: grafana
    environment: {{ .Values.environment }}
spec:
  ports:
    - port: 9091
      targetPort: 3000
      nodePort: 30091
  selector:
    app: double-entry-book-keeping
    tier: grafana
    environment: {{ .Values.environment }}
  type: NodePort
