# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: double-entry-book-keeping
    tier: prometheus
    environment: {{ .Values.environment }}
spec:
  selector:  
    matchLabels:
      app: double-entry-book-keeping
      tier: prometheus
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: double-entry-book-keeping
        tier: prometheus
        environment: {{ .Values.environment }}
    spec:
      serviceAccountName: prometheus-service-account
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            # https://prometheus.io/docs/prometheus/latest/feature_flags/#remote-write-receiver
            - "--enable-feature=remote-write-receiver"
            # https://prometheus.io/docs/prometheus/latest/feature_flags/#native-histograms
            - "--enable-feature=native-histograms"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
            - name: prometheus-data-volume
              mountPath: /prometheus
          resources:
            requests:
              cpu: {{ .Values.prometheus.resources.requests.cpu }}
              memory: {{ .Values.prometheus.resources.requests.memory }}
            limits: 
              cpu: {{ .Values.prometheus.resources.limits.cpu }}
              memory: {{ .Values.prometheus.resources.limits.memory }}
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            defaultMode: 0444
        - name: prometheus-data-volume
          emptyDir: {}
