# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: double-entry-book-keeping
    tier: prometheus
    environment: {{ .Values.environment }}
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: double-entry-book-keeping
    tier: prometheus
    environment: {{ .Values.environment }}
  type: NodePort
